parameters:
    web_consul_ebay_api.main.class: WebConsul\EbayApiBundle\Call\BaseCall
    web_consul_ebay_api.make_call.class: WebConsul\EbayApiBundle\Service\MakeCallService
    web_consul_ebay_api.finding.class: WebConsul\EbayApiBundle\Service\FindingService
    web_consul_ebay_api.shopping.class: WebConsul\EbayApiBundle\Service\ShoppingService
    web_consul_ebay_api.trading.class: WebConsul\EbayApiBundle\Service\TradingService

services:
    web_consul_ebay_api.main:
        class: "%web_consul_ebay_api.main.class%"
        arguments:
            - "%web_consul_ebay_api%"
    web_consul_ebay_api.make_call:
        class: "%web_consul_ebay_api.make_call.class%"
        arguments:
            -  "@jms_serializer"
    web_consul_ebay_api.finding:
        class: "%web_consul_ebay_api.finding.class%"
    web_consul_ebay_api.shopping:
        class: "%web_consul_ebay_api.shopping.class%"
    web_consul_ebay_api.trading:
        class: "%web_consul_ebay_api.trading.class%"
